development:
  adapter: postgresql
  encoding: unicode
  database: to-do-list-development
  pool: 5
  host: localhost
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: to-do-list-test
  pool: 5
  host: localhost
  template: template0


production:
  adapter: postgresql
  encoding: unicode
  database: to-do-list-prod
  pool: 5
  host: localhost
  template: template0
